# Numpy 

1 - Basically a python library used for fast numerical computation

In [1]:
# step 1: importing numpy 
import numpy as np

In [3]:
# step 2 : creating a Arrays
# the way data is store in an array is in dimensional form


# 1Dimensional Array
array_1d = np.array( [1,2,3,5]  )
array_1d


array([1, 2, 3, 5])

#### 1D (A single column)
[1,2,3,4,5]

- shape 
    - (n,) --1 single column without rows

    (a--column,b-rows)
    (n,)


### 2D (A table or matrix with rows and columns)
- shape
    - (m, n)--- number of rows (m)
            ---- number of columns (n)
    - [1,2,3]
    - [4,5,6]

### 3D ( a stack of 2D array, a multiple tables)

- shape 
 (p, m, n) 
 - p = number of matrices
 - m = columns per matrix
 - n - rows per matrix

[1,2,3]   
[4,5,6]         

[7,8,9]     
[10,11,12]

In [ ]:
# 2D - dimension Array
array_2d = np.array( [ [1,2,3,4,5], [6,7,8,9,10]  ]  )
print(array_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# 3D - dimension array
array_3d = np.array(
    [
        [ [1,2,3,4,5], [6,7,8,9,10] ],               #2D array ---- #3D array
        [ [11,12,13,14,15], [16,17,18,19,20] ],     #2D array
    ]
)

In [ ]:
# step 3 - Zeros & Ones

# Generate set of 0s
zeros = np.zeros( [5, 3] )  #  # 5 rows and 3 columns
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Generate set of 1's
ones = np.ones( (2,3)  )   # 2 rows and 3 columns
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
#generate random number within a range and shape

rand = np.random.randint(0,1000, (4,3)) #4 rows and 3 columns
print(rand)

[[886 280 771]
 [414 480 860]
 [354 772 962]
 [589  55 357]]


In [15]:
# Step 4 Arithmetic Operations within ARRAY

 #- addition 
 #- multiplications
 #- mean (Average)

array_one = np.array( [1,2,3,5])
array_two = np.array( [6,7,8,9] )

#addition
additon = array_one + array_two
multiplication = array_one * array_two
average = np.mean(array_one)

print(additon)
print(multiplication)
print(average)



[ 7  9 11 14]
[ 6 14 24 45]
2.75
